VALIDATION_FEATURES_DEF = './datasets/raw/merged_val.npy'
VALIDATION_CAPTIONS_DEF = './datasets/raw/merged_val.json'
TRAIN_FEATURES_DEF      = './datasets/raw/merged_train.npy'
TRAIN_CAPTIONS_DEF      = './datasets/raw/merged_train.json'
PROCESSED_FOLDER        = './datasets/processed/'
